# Ejercicios

In [1]:
import numpy as np

## Numpy Arrays

**Ejercicio 1**: Crear un arreglo NumPy 1D de 5 elementos con valores enteros del 0 al 4.

In [2]:
arr = np.array([0, 1, 2, 3, 4])
print(arr)

[0 1 2 3 4]


**Ejercicio 2**: Crear un arreglo NumPy 2D de 3x3 con todos los elementos igual a 1.ual a 1.

In [3]:
arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



**Ejercicio 3**: Crear un arreglo NumPy 1D de 10 elementos con valores equidistantes entre 0 y 1.

In [4]:
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


**Ejercicio 4**: Crear un arreglo NumPy 2D de 3x3 con valores aleatorios entre 0 y 1.

In [5]:
arr = np.random.rand(3, 3)
print(arr)

[[0.41951944 0.06979298 0.18179434]
 [0.62465905 0.77333522 0.6738003 ]
 [0.35120366 0.02928759 0.84761288]]


**Ejercicio 5**: Crear un arreglo NumPy 1D con números enteros pares del 0 al 10.

In [6]:
arr = np.arange(0, 11, 2)
print(arr)

[ 0  2  4  6  8 10]


**Ejercicio 6**: Crear un arreglo NumPy 2D de 4x4 con números enteros aleatorios en el rango de 1 a 10.

In [7]:
arr = np.random.randint(1, 11, (4, 4))
print(arr)

[[ 8  4  9  5]
 [ 8 10  6 10]
 [ 7  6  7  8]
 [ 3  9  6  7]]


**Ejercicio 7**: Crear un arreglo NumPy 1D con los primeros 5 números primos.

In [8]:
primes = np.array([2, 3, 5, 7, 11])
print(primes)

[ 2  3  5  7 11]


**Ejercicio 8**: Crear un arreglo NumPy 1D con valores de 0 a 9 y luego invertir el orden de los elementos.

In [9]:
arr = np.arange(10)
arr_inverted = arr[::-1]
print(arr_inverted)

[9 8 7 6 5 4 3 2 1 0]


**Ejercicio 9**: Dado un arreglo NumPy 1D, calcular la suma de sus elementos.

In [10]:
arr = np.array([1, 2, 3, 4, 5])
suma = np.sum(arr)
print(suma)

15


**Ejercicio 10**: Dado un arreglo NumPy 2D, calcular la suma de cada columna por separado.

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
suma_columnas = np.sum(arr, axis=0)
print(suma_columnas)

[12 15 18]


## Operaciones Matemáticas

**Ejercicio 1:** Encuentra la suma, resta, multiplicación y división de dos arreglos NumPy de 1D `a` y `b`.

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [13]:
suma = a + b
resta = a - b
multiplicacion = a * b
division = a / b

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

Suma: [ 6  8 10 12]
Resta: [-4 -4 -4 -4]
Multiplicación: [ 5 12 21 32]
División: [0.2        0.33333333 0.42857143 0.5       ]


**Ejercicio 2:** Calcula el promedio, la mediana y la desviación estándar de un arreglo NumPy 1D `datos`.

In [14]:
datos = np.array([10, 15, 20, 25, 30, 35, 40])

In [15]:
promedio = np.mean(datos)
mediana = np.median(datos)
desviacion_estandar = np.std(datos)

print("Promedio:", promedio)
print("Mediana:", mediana)
print("Desviación Estándar:", desviacion_estandar)

Promedio: 25.0
Mediana: 25.0
Desviación Estándar: 10.0


**Ejercicio 3:** Calcula el producto punto de dos arreglos NumPy 1D `a` y `b`.

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [17]:
producto_punto = np.dot(a, b)

print("Producto Punto:", producto_punto)

Producto Punto: 32


**Ejercicio 4:** Encuentra el valor mínimo y máximo en un arreglo NumPy 1D `valores`.

In [18]:
valores = np.array([5, 8, 2, 10, 3])

In [19]:
minimo = np.min(valores)
maximo = np.max(valores)

print("Valor Mínimo:", minimo)
print("Valor Máximo:", maximo)

Valor Mínimo: 2
Valor Máximo: 10


**Ejercicio 5:** Calcula la suma acumulativa de un arreglo NumPy 1D `serie`.

In [20]:
serie = np.array([1, 2, 3, 4, 5])

In [21]:
suma_acumulativa = np.cumsum(serie)

print("Suma Acumulativa:", suma_acumulativa)

Suma Acumulativa: [ 1  3  6 10 15]


**Ejercicio 6:** Calcula el promedio de cada fila y cada columna en un arreglo NumPy 2D `matriz`.

In [22]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
promedio_filas = np.mean(matriz, axis=1)
promedio_columnas = np.mean(matriz, axis=0)

print("Promedio por Filas:", promedio_filas)
print("Promedio por Columnas:", promedio_columnas)

Promedio por Filas: [2. 5. 8.]
Promedio por Columnas: [4. 5. 6.]


**Ejercicio 7:** Calcula la potencia de un arreglo NumPy 1D `numeros` al cuadrado.

In [24]:
numeros = np.array([2, 3, 4, 5, 6])

In [25]:
cuadrado = np.power(numeros, 2)

print("Cuadrado:", cuadrado)

Cuadrado: [ 4  9 16 25 36]


**Ejercicio 8:** Encuentra el valor absoluto de un arreglo NumPy 1D `valores`

In [26]:
valores = np.array([-3, 5, -7, 8, -2])

In [27]:
valor_absoluto = np.abs(valores)

print("Valor Absoluto:", valor_absoluto)

Valor Absoluto: [3 5 7 8 2]


**Ejercicio 9:** Calcula la media ponderada de un arreglo NumPy 1D `datos` con pesos correspondientes en el arreglo `pesos`.

In [28]:
datos = np.array([10, 15, 20, 25, 30])
pesos = np.array([0.1, 0.2, 0.3, 0.2, 0.2])

In [29]:
media_ponderada = np.average(datos, weights=pesos)

print("Media Ponderada:", media_ponderada)

Media Ponderada: 21.0


**Ejercicio 10:** Calcula el producto de matrices de dos arreglos NumPy 2D `matriz_a` y `matriz_b`.

In [30]:
matriz_a = np.array([[1, 2], [3, 4]])
matriz_b = np.array([[5, 6], [7, 8]])

In [31]:
producto_matrices = np.dot(matriz_a, matriz_b)

print("Producto de Matrices:")
print(producto_matrices)

Producto de Matrices:
[[19 22]
 [43 50]]


## Indexación

**Ejercicio 1:** Extraer el tercer elemento de un arreglo NumPy 1D `arr`.

**Ejercicio 2:** Extraer una subserie de un arreglo NumPy 1D `arr` que contenga elementos desde el segundo al cuarto (inclusive).

**Ejercicio 3:** Extraer los elementos pares de un arreglo NumPy 1D `numeros`.

**Ejercicio 4:** En un arreglo NumPy 2D `matriz`, extraer la segunda fila y la tercera columna.

**Ejercicio 5:** En un arreglo NumPy 2D `matriz`, extraer todos los elementos que sean mayores que 5.

**Ejercicio 6:** Crear una vista de un arreglo NumPy 1D `original` que contenga solo los elementos desde el segundo al quinto (inclusive).

**Ejercicio 7:** En un arreglo NumPy 2D `matriz`, extraer los elementos de la segunda fila que sean mayores que 3.

**Ejercicio 8:** Crear una vista de un arreglo NumPy 2D `original` que contenga solo la primera y la última fila.

**Ejercicio 9:** En un arreglo NumPy 2D `matriz`, extraer las filas pares.

**Ejercicio 10:** En un arreglo NumPy 2D `matriz`, reemplazar todos los elementos mayores que 5 por el valor 0.