# Objetos en Numpy

<img src="https://i1.wp.com/indianaiproduction.com/wp-content/uploads/2019/06/NumPy-array.png?resize=768%2C368&ssl=1" align="center"/>

En NumPy, el objeto principal es el **array multidimensional** (llamado `ndarray`), que es una estructura de datos eficiente para el procesamiento de datos numéricos. Los arrays en NumPy son objetos homogéneos y de tamaño fijo que contienen elementos del mismo tipo de datos.

Aquí hay algunos ejemplos de objetos en NumPy:

In [1]:
import numpy as np

# Crear un array 1D de longitud 3
arr_1d = np.array([1, 2, 3])
print(arr_1d)

[1 2 3]


In [2]:
# Crear un array 2D de tamaño 2x3
arr_2d = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [5]:
# Crear un array 3D de tamaño 2x2x3
arr_3d = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Veamos algunos atributos de los arreglos en Numpy:

* `ndarray.shape`: devuelve la forma (dimensiones) del array.
* `ndarray.ndim`: devuelve el número de dimensiones del array.
* `ndarray.size`: devuelve el número total de elementos en el array.
* `ndarray.dtype`: devuelve el tipo de datos de los elementos del array.


In [7]:
# crear objeto
obj_numpy =np.array(
    [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# shape
obj_numpy.shape

(9,)

In [9]:
# ndim
obj_numpy.ndim

1

In [ ]:
# size
obj_numpy.size

In [10]:
# dtype
obj_numpy.dtype

dtype('int32')