<a href="https://colab.research.google.com/github/fralfaro/python_eda/blob/main/docs/numpy/022_operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operaciones

NumPy proporciona una variedad de **operaciones básicas** que se pueden realizar en los arrays, como operaciones aritméticas, operaciones de comparación y operaciones de agregación. Aquí hay algunos ejemplos de operaciones básicas en NumPy:



## Operaciones aritméticas


In [3]:
import numpy as np

# Crear dos arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [4]:
# Suma de arrays
c = a + b
print(c)

[5 7 9]


In [5]:
# Resta de arrays
c = a - b
print(c)

[-3 -3 -3]


In [6]:
# Multiplicación de arrays
c = a * b
print(c)

[ 4 10 18]


In [7]:
# División de arrays
c = a / b
print(c)

[0.25 0.4  0.5 ]


## Operaciones de comparación

In [8]:
# Crear dos arrays
a = np.array([1, 2, 3])
b = np.array([2, 2, 4])

In [9]:
# Comparación de arrays
c = a == b
print(c)

[False  True False]


In [10]:
# Comparación de arrays
c = a > b
print(c)

[False False False]


In [11]:
# Comparación de arrays
c = a <= b
print(c)

[ True  True  True]


## Operaciones de estadísticas

In [16]:
# Crear un array
a = np.array([1, 2, 3, 4, 5])

# Suma de los elementos en un array
sum_a = np.sum(a)
print(f"Suma de elementos: {sum_a}")

Suma de elementos: 15


In [17]:
# Mínimo y máximo de los elementos en un array
min_a = np.min(a)
max_a = np.max(a)

print(f"minimo: {min_a}")
print(f"maximo: {max_a}")

minimo: 1
maximo: 5


In [18]:
# Promedio y desviación estándar de los elementos en un array
mean_a = np.mean(a)
std_a = np.std(a)

print(f"promedio: {mean_a}")
print(f"desviacion estandar: {std_a}")

promedio: 3.0
desviacion estandar: 1.4142135623730951
