<a href="https://colab.research.google.com/github/fralfaro/python_eda/blob/main/docs/numpy/023_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexación 

La **indexación** en NumPy es similar a la indexación en listas de Python, pero se extiende a múltiples dimensiones. En NumPy, los arrays se pueden indexar y rebanar para acceder a elementos y subarrays específicos. Aquí hay algunos ejemplos de indexación en NumPy:

* **Acceder a elementos individuales de un array unidimensional**:


In [ ]:
import numpy as np

# Crear un array unidimensional
a = np.array([1, 2, 3, 4, 5])

In [ ]:
# Acceder al primer elemento
print(a[0])

In [ ]:
# Acceder al último elemento
print(a[-1])

In [1]:
# Acceder al tercer elemento
print(a[2])

1
5
3


* **Acceder a elementos individuales de un array multidimensional**:

In [14]:
# Crear un array bidimensional
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)

In [3]:
# Acceder al primer elemento
print(b[0, 0])

1


In [4]:
# Acceder al último elemento
print(b[-1, -1])

9


In [5]:
# Acceder al elemento en la segunda fila y tercer columna
print(b[1, 2])

6


* **Rebanar un array unidimensional**:


In [6]:
# Rebanar un array unidimensional
a = np.array([1, 2, 3, 4, 5])

In [7]:
# Rebanar los primeros tres elementos
print(a[:3])

[1 2 3]


In [8]:
# Rebanar los últimos dos elementos
print(a[-2:])

[4 5]


In [9]:
# Rebanar todos los elementos saltando de dos en dos
print(a[::2])

[1 3 5]


* **Rebanar un array multidimensional**:

In [15]:
# Rebanar un array bidimensional
b = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]]
)

In [11]:
# Rebanar la primera y segunda fila
print(b[:2, :])

[[1 2 3]
 [4 5 6]]


In [12]:
# Rebanar la segunda y tercera columna
print(b[:, 1:])

[[2 3]
 [5 6]
 [8 9]]


In [13]:
# Rebanar la diagonal principal
print(b.diagonal())

[1 5 9]
